"""Prepare a native H3 image job from an existing, exact P552/Qwen view binding.

No planner, Qwen request, renderer or image model is executed here.  Only an
already recorded target-appearance description is reused.  Coordinates are
copied from the selected geometric crop; none are generated by this module.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import sys

from PIL import Image

from .image_contract import artifact, read_sealed, require, verified, write_receipt


HERE = Path(__file__).resolve().parent
JOB_SCHEMA = "p553.reference_single_image_job.v1"


def _json(path):
    value = json.loads(Path(path).read_text(encoding="utf-8"))
    require(isinstance(value, dict), "Expected an object receipt")
    return value


def _check_route(stage1_path):
    from hsi.stage1.navigation import check_stage1_handoff
    return check_stage1_handoff(stage1_path)


def _validate_description(description, description_path, stage1, view_path, selected):
    require(description.get("schema") == "p550.view_bound_target_description.v1", "Wrong target-description schema")
    require(description.get("target") == stage1["target"], "Description belongs to another target")
    require(description.get("view") == artifact(view_path), "Description belongs to another selected view")
    semantic = description.get("semantic")
    require(isinstance(semantic, dict) and set(semantic) == {"target_visual_identity", "needs_more_evidence"},
            "Unexpected target-description fields")
    require(semantic["needs_more_evidence"] is False, "Target identity remains ambiguous")
    identity = semantic["target_visual_identity"]
    require(isinstance(identity, str) and 12 <= len(identity) <= 280, "Invalid existing target appearance")
    generation = description.get("generation")
    require(isinstance(generation, dict), "Description lacks actual Qwen generation provenance")
    call_path = Path(generation.get("call_receipt", "")).resolve(strict=True)
    call = _json(call_path)
    require(call.get("status") == "complete" and call.get("result") == generation,
            "Description differs from the actual Qwen call result")
    require(str(generation.get("model_id", "")).startswith("Qwen/"), "Description was not produced by Qwen")
    require(call.get("model", {}).get("model_id") == generation["model_id"], "Qwen model provenance drift")
    require(json.loads(generation.get("raw_completion", "null")) == semantic,
            "Description differs from the recorded raw Qwen completion")
    require(call.get("response", {}).get("choices", [{}])[0].get("message", {}).get("content")
            == generation["raw_completion"], "Qwen response content differs from the description")
    require(hashlib.sha256(call.get("prompt", "").encode()).hexdigest() == generation.get("prompt_sha256"),
            "Qwen target-description prompt hash drift")
    evidence = call.get("image_evidence")
    require(isinstance(evidence, list) and len(evidence) == 2, "Target description needs the original two Qwen images")
    expected = [selected["selected_stage2_crop"], selected["selected_stage2_crop_target_overlay"]]
    for index, (record, wanted) in enumerate(zip(evidence, expected)):
        require(isinstance(record, dict) and record.get("label") == f"IMAGE_{index}", "Qwen image order changed")
        observed = {key: record.get(key) for key in ("path", "bytes", "sha256")}
        require(observed == wanted, "Qwen description used another crop or target overlay")
        verified(observed, "recorded Qwen description image")
    return identity, artifact(call_path)


def validate_inputs(stage1_path, view_path, description_path):
    stage1_path, view_path, description_path = [Path(p).resolve(strict=True)
                                               for p in (stage1_path, view_path, description_path)]
    stage1, view, description = map(read_sealed, (stage1_path, view_path, description_path))
    from .views import validate_receipt as validate_current_view
    require(validate_current_view(view_path, stage1_path) == view, "Current view validation differs")
    require(stage1.get("status") == "complete", "A completed P552 Stage1 execution is required")
    require("p552_contact_region_guard" in stage1, "A P552 route-region guard is required")
    guard_path = verified(stage1["p552_contact_region_guard"], "P552 route guard")
    guard = _check_route(stage1_path)
    require(guard.get("all_gates_passed") is True and bool(guard.get("quality_gates"))
            and all(item is True for item in guard["quality_gates"].values()), "P552 route-region handoff failed")
    require(view.get("source_stage1_execution") == artifact(stage1_path), "Selected view belongs to another plan")
    require(view.get("publication", {}).get("stage2_generation_handoff_allowed") is True,
            "View has not passed geometric visibility screening")
    selected = view.get("selection")
    require(isinstance(selected, dict), "Missing actual selected view")
    for key in ("selected_source_rgb", "selected_camera", "selected_stage2_crop", "selected_stage2_crop_target_overlay"):
        verified(selected.get(key), key)
    require(type(selected.get("selected_view_index")) is int and selected["selected_view_index"] >= 0,
            "Invalid selected view index")
    target = read_sealed(verified(stage1["target"], "Stage1 target"))
    verified(stage1["bundle"], "Stage1 bundle")
    require(target.get("scene_id") == stage1["scene_id"], "Target belongs to another scene")
    renderer = read_sealed(verified(view["source_render"], "source render receipt"))
    require(renderer.get("scene_id") == stage1["scene_id"], "Render belongs to another scene")
    for render_name, target_name in (("original_scene_mesh", "original_scene_mesh"), ("query_occupancy", "scene_occupancy")):
        source = renderer.get("inputs", {}).get(render_name)
        require(source == target.get("artifacts", {}).get(target_name), "Render/target scene-source binding drift")
        verified(source, render_name)
    candidates = [row for row in renderer["views"] if row.get("view_index") == selected["selected_view_index"]]
    require(len(candidates) == 1, "Selected camera is not a unique recorded render view")
    rendered = candidates[0]
    require(rendered.get("camera") == selected["selected_camera"]
            and rendered.get("rgb") == selected["selected_source_rgb"], "Selected camera/RGB render binding drift")
    camera = _json(verified(selected["selected_camera"], "selected camera"))
    require(camera.get("extrinsic_convention") == "opencv_world_to_camera", "Invalid source camera convention")
    crop = selected.get("selected_crop_xyxy")
    require(isinstance(crop, list) and len(crop) == 4 and all(type(x) is int for x in crop), "Invalid geometric crop")
    x0, y0, x1, y1 = crop
    require(0 <= x0 < x1 <= camera["width"] and 0 <= y0 < y1 <= camera["height"], "Crop is outside source camera")
    with Image.open(verified(selected["selected_source_rgb"])) as rgb:
        require(rgb.size == (camera["width"], camera["height"]), "Source camera/RGB size mismatch")
    with Image.open(verified(selected["selected_stage2_crop"])) as image:
        require(image.format == "PNG" and image.mode == "RGB" and image.size == (512, 512)
                and getattr(image, "n_frames", 1) == 1, "Condition must be a static RGB 512-square PNG")
    identity, call = _validate_description(description, description_path, stage1, view_path, selected)
    return {"stage1": stage1, "view": view, "target": target, "selected": selected,
            "identity": identity, "actual_qwen_call": call, "guard": artifact(guard_path)}


def image_prompt(identity):
    return (
        "<Picture 1> is the reference scene. Preserve its exact fixed camera, room, furniture, "
        "textures, lighting and background. Add exactly one realistic, opaque clothed adult "
        "seated on this exact existing target furniture: " + identity + " "
        "Create a clear full-body static sitting keypose. The pelvis and upper thighs are "
        "supported by the existing seat, the back is upright, the knees are naturally bent, "
        "and both separated feet rest on the floor in front of the seat. Both arms rest "
        "naturally without hiding the legs. Include the complete head and both feet in the image. "
        "Do not move, replace, deform or add furniture. Do not seat the person on the floor, "
        "table, armrest or a different seat. Preserve the background geometry of <Picture 1>."
    )


def validate_job(path):
    """Recompute the current plan/view/Qwen identity chain before inference.

    This validates this package's actual builder and geometry evidence; a
    caller-supplied success flag or a saved crop alone is not accepted.
    """
    job = read_sealed(path)
    require(job.get('schema') == JOB_SCHEMA and job.get('operation') == 'reference_single_image',
        'Expected a bound reference-single-image job')
    require(isinstance(job.get('case_id'), str) and re.fullmatch(r'[A-Za-z0-9_-]+', job['case_id']),
        'Invalid case ID')
    require(type(job.get('seed')) is int and job['seed'] >= 0, 'Invalid image seed')
    names = ('stage1_execution', 'camera', 'crop_derivation', 'condition_source')
    require(set(job.get('job_source_bindings', {})) == set(names), 'Unexpected job source fields')
    for name in names:
        require(artifact(job[name]) == job['job_source_bindings'][name], 'Job source drift: ' + name)
    origin = read_sealed(verified(job['origin_receipt_binding']))
    require(origin['source'] == artifact(__file__), 'Job was built by another source version')
    checked = validate_inputs(job['stage1_execution'], verified(origin['source_view']),
        verified(origin['source_target_description']))
    selected = checked['selected']
    require(job['prompt'] == image_prompt(checked['identity']), 'Prompt differs from current target appearance')
    condition = artifact(job['condition_source'])
    require(all(condition[k] == selected['selected_stage2_crop'][k] for k in ('sha256', 'bytes')),
        'Job condition differs from actual selected crop')
    require(artifact(job['camera']) == selected['selected_camera'], 'Job camera mismatch')
    expected_origin = {
        'stage1_execution': artifact(job['stage1_execution']), 'source_target': checked['stage1']['target'],
        'source_stage1_bundle': checked['stage1']['bundle'], 'route_contact_region_guard': checked['guard'],
        'source_render': checked['view']['source_render'], 'source_selected_crop': selected['selected_stage2_crop'],
        'condition_copy': condition, 'camera': selected['selected_camera'],
        'source_selected_overlay': selected['selected_stage2_crop_target_overlay'],
        'actual_existing_qwen_call': checked['actual_qwen_call'], 'target_visual_identity': checked['identity'],
    }
    require(all(origin.get(k) == v for k, v in expected_origin.items()), 'Image origin binding differs')
    crop = read_sealed(job['crop_derivation'])
    expected_crop = {
        'origin_receipt_binding': job['origin_receipt_binding'], 'source_view': origin['source_view'],
        'source_stage1_execution': origin['stage1_execution'], 'source_stage1_target': origin['source_target'],
        'source_camera': origin['camera'], 'source_selected_crop': origin['source_selected_crop'],
        'crop_xyxy': selected['selected_crop_xyxy'], 'output_size_wh': [512, 512],
        'condition_image': condition, 'qwen_input_image': condition,
    }
    require(all(crop.get(k) == v for k, v in expected_crop.items()), 'Image crop derivation differs')
    return job


def run(*, stage1_path, view_path, description_path, output, case_id, seed):
    require(isinstance(case_id, str) and re.fullmatch(r"[A-Za-z0-9_-]+", case_id), "Unsafe or missing case ID")
    require(type(seed) is int and seed >= 0, "Seed must be a nonnegative integer")
    output = Path(output).resolve()
    require(not output.exists(), "Refusing to overwrite an existing image job")
    checked = validate_inputs(stage1_path, view_path, description_path)
    stage1, target, selected = checked["stage1"], checked["target"], checked["selected"]
    output.mkdir(parents=True, exist_ok=False)
    condition_path = output / "condition_source.png"
    shutil.copy2(verified(selected["selected_stage2_crop"]), condition_path)
    condition = artifact(condition_path)
    require(all(condition[key] == selected["selected_stage2_crop"][key] for key in ("bytes", "sha256")),
            "Copied condition image differs from the fixed selected crop")
    origin_path = output / "origin_receipt_binding.json"
    origin = {
        "schema": "p553.existing_plan_view_qwen_identity_binding.v1", "source": artifact(__file__),
        "stage1_execution": artifact(stage1_path), "source_view": artifact(view_path),
        "source_target_description": artifact(description_path), "actual_existing_qwen_call": checked["actual_qwen_call"],
        "source_target": stage1["target"], "source_stage1_bundle": stage1["bundle"],
        "route_contact_region_guard": checked["guard"], "source_render": checked["view"]["source_render"],
        "source_selected_crop": selected["selected_stage2_crop"], "condition_copy": condition,
        "camera": selected["selected_camera"], "source_selected_overlay": selected["selected_stage2_crop_target_overlay"],
        "target_visual_identity": checked["identity"], "qwen_new_call_performed": False,
        "qwen_generated_coordinates": False, "all_inputs_bind_to_same_plan_target_and_selected_view": True,
        "actual_h3_generation_performed": False, "stage2_keypose_publication_claimed": False,
    }
    write_receipt(origin_path, origin)
    derivation_path = output / "input_derivation.json"
    derivation = {
        "schema": "p553.fixed_geometric_crop_for_reference_single_image.v1",
        "status": "complete_target_bound_crop", "consumer": "MiniMax-H3 reference_single_image",
        "source": artifact(__file__), "origin_receipt_binding": artifact(origin_path),
        "scene_id": stage1["scene_id"], "instruction": stage1["instruction"],
        "target_instance_id": target["target_instance_id"], "source_stage1_execution": artifact(stage1_path),
        "source_stage1_target": stage1["target"], "source_view_index": selected["selected_view_index"],
        "source_rgb": selected["selected_source_rgb"], "source_camera": selected["selected_camera"],
        "source_selected_crop": selected["selected_stage2_crop"], "source_view": artifact(view_path),
        "crop_xyxy": selected["selected_crop_xyxy"], "output_size_wh": [512, 512],
        "condition_image": condition, "qwen_input_image": condition,
        "legacy_qwen_input_image_field_is_condition_alias_only": True,
        "condition_pixels_copied_exactly": True, "crop_coordinates_copied_from_verified_geometry": True,
        "qwen_generated_coordinates": False, "qwen_image_generator_used": False,
        "qwen_new_call_performed": False, "video_generation_requested": False,
    }
    write_receipt(derivation_path, derivation)
    job = {"schema": JOB_SCHEMA, "case_id": case_id, "seed": seed,
        "prompt": image_prompt(checked["identity"]), "stage1_execution": str(Path(stage1_path).resolve()),
        "camera": selected["selected_camera"]["path"], "crop_derivation": str(derivation_path),
        "condition_source": str(condition_path), "origin_receipt_binding": artifact(origin_path),
        "job_source_bindings": {"stage1_execution": artifact(stage1_path), "camera": selected["selected_camera"],
            "crop_derivation": artifact(derivation_path), "condition_source": condition},
        "operation": "reference_single_image", "actual_h3_generation_performed": False,
        "qwen_new_call_performed": False, "qwen_generated_coordinates": False}
    write_receipt(output / "single_image_job.json", job)
    return job


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    for name in ("stage1", "view", "target-description", "output"):
        parser.add_argument("--" + name, type=Path, required=True)
    parser.add_argument("--case-id", required=True)
    parser.add_argument("--seed", type=int, required=True)
    args = parser.parse_args()
    job = run(stage1_path=args.stage1, view_path=args.view, description_path=args.target_description,
              output=args.output, case_id=args.case_id, seed=args.seed)
    print(json.dumps({"job": str(args.output / "single_image_job.json"), "case_id": job["case_id"],
                      "model_calls_performed": 0}, ensure_ascii=False))


if __name__ == "__main__":
    main()
